spawnentry:
  x: 50.0
  y: 64.0
  z: 50.0

zlareas:
  1:
    x1: 75.0
    x2: 125.0
    z1: 75.0
    z2: 125.0
    entry:
      x: 100.0
      y: 64.0
      z: 100.0

zlrules:
  pauseTime: 30
  playerLives: 3

teams:
  red
  green
  blue
  yellow