spawnentry:
  x: 50.0
  y: 4.0
  z: 50.0

zlareas:
  1:
    x1: 75.0
    x2: 125.0
    z1: 75.0
    z2: 125.0
    entry:
      x: 100.0
      y: 5.0
      z: 100.0
    options:
      maxLevel: 5
      pauseTime: 30
      playerLives: 3

zllevels:
  1:
    Zombie1: 3
  2:
    Zombie1: 7
  3:
    Zombie1: 10
  4:
    Zombie1: 13
  5:
    Zombie1: 17
  6:
    Zombie1: 20

teams:
  red: red
  green: green
  blue: blue
  yellow: yellow